export const containers = {
  platforms: "platforms",
  news: "news",
  topics: "topics",
  config: "config",
  subscribers: "subscribers",
  contactSubmissions: "contact-submissions",
  businessConfig: "business-config",
  businessCustomers: "business-customers",
  businessVendors: "business-vendors",
  businessInvoices: "business-invoices",
  businessPayments: "business-payments",
  businessBankAccounts: "business-bank-accounts",
  businessBankTransactions: "business-bank-transactions",
  businessJournalEntries: "business-journal-entries",
  businessImportJobs: "business-import-jobs",
  businessImportSources: "business-import-sources",
  businessImportArtifacts: "business-import-artifacts",
  businessReconcileRuns: "business-reconcile-runs",
  businessAuditEvents: "business-audit-events",
};

export const partitions = {
  news: "/id",
  // Small sets may use constant partition keys; configure on container creation.
  businessConfig: "/pk",
  businessCustomers: "/pk",
  businessVendors: "/pk",
  businessInvoices: "/pk",
  businessPayments: "/pk",
  businessBankAccounts: "/pk",
  businessAuditEvents: "/dateBucket",
  businessBankTransactions: "/bankAccountId",
  businessJournalEntries: "/fiscalYear",
  businessImportSources: "/pk",
  businessImportJobs: "/pk",
  businessReconcileRuns: "/pk",
};
